### ISSUE TITLE
Looking for advice

### ISSUE THREAD

**Issue by ahmed658** [amrsekilly/AMA#10]
I've been studying Data Structures and Algorithms for 6 months, I am majoring in Business so mathematics isn't a thing am familiar with. That didn't stop me and I dedicated 4 months to study college algebra, calculus, and discrete math. I can finally tell that I have a sense of mathematical maturity now since I can read and understand proofs in engineering books like CLRS. I wrote most of the well-known data structures and algorithms using Java. The course I was auditing had a final project near the end giving a task of writing a priority queue using min heap implementation and adding extra functionalities to it with a specific time complexity, then implementing an A* algorithm and combining both in writing a part of the backend of a mapping application. This project took me a considerable amount of time but it gave me a solid foundation and understanding of different data structures and algorithms and how to use them in solving problems. I am confused now between two choices, the first is to learn design patterns and a framework to start freelancing or applying for jobs. The second choice is to continue with studying computer science and delve into other branches like operating systems, computer architecture, database design, and distributed systems. I am interested in finding a job and making money ASAP as my dad has just died during the pandemic, but on the other hand I fear that I would be missing out future opportunities if I didn't complete my studies of the CS curriculum. Needless to say I am familiar with OOP principles already and can solve most of the problems on LeetCode and HackerRank.

**Comment by amrsekilly** [comment]
Hi Ahmed, first of all I'm so sorry for your loss. Second, really sorry for the late reply, I just saw your issue now as I was busy.

My suggestion would be to learn a framework and try to land a job ASAP. Let me know if I can help with that in any way @ahmed658
