### ISSUE TITLE
How to get a remote  job as a junior developer or have basic experience?

### ISSUE THREAD

**Issue by MostafaSalama** [amrsekilly/AMA#3]
Hi, I want to know how to get a remote job if I'm a junior developer or have the basic experience, my expertise is in full-stack development (Javascript stack), I want to know the requirement that you think  I should have or the things that I should do to get a remote job, also any skills that you think are important ( tech or non-tech skills ).

Thank you.

**Comment by amrsekilly** [comment]
Hi @MostafaSalama! 

Sorry for the delay, I've answered your question here: https://www.youtube.com/watch?v=K-8EA2qNKhs

Let me know if you have any other questions.
