### ISSUE TITLE
اسف جدا علي التأخير يا بشمهندس

### ISSUE THREAD

**Issue by ghost** [amrsekilly/AMA#5]
اسف جدا علي التأخير اعذرني يا بشمهندس لسة عامل github الاسبوع ده

انا عملت اول صفحة من تيمبلت شغال عليه اهو لو سمحت بص بصة عليه وقولي رأي حضرتك ايه لغاية بس ما اكمله وارفع باقي المشاريع ان شاء الله

عاوز اعرف لو سمحت ده نوع التيمبلتس اللي اقدر احطها في السي في ولا انا كده ماشي غلط وشكرا لحضرتك علي اهتمامك ♥

https://github.com/geekcoder22/business-startup

https://startup-business.netlify.app/

**Comment by amrsekilly** [comment]
@geekcoder22 are you okay with having a recorded zoom meeting that I can upload to Youtube after editing? If not, I can reply here in text.

**Comment by ghost** [comment]
اتفضل يا بشمهندس براحتك ♥
انا بشكر حضرتك علي اهتمامك وردك عليا جزاك الله خيرا

**Comment by amrsekilly** [comment]
@geekcoder22 can you send me your email to schedule this call with you?

**Comment by ghost** [comment]
انا اسف جدا انا فهمت غلط 
اتفضل يا بشمهندس ده ايميلي ولكن انا معنديش كاميرا ولا مايك للاسف ولا حتي اسمارت فون هو موبايل معفن بزراير بتاع زمان ده والكمبيوتر اللي بذاكر عليه 
اعذرني علي سوء الفهم الانجلش بتاعي مش قوي للاسف
geekcoder75@gmail.com

**Comment by amrsekilly** [comment]
@geekcoder22 بص هو حلو. بس مينفعش تستخدمه زي ما هو كدة. 

أنصحك تعمله rebranding 

يعني متحطوش كتيمبليت. خليه بروجيكت لشركة حقيقية وحط فيه بيانات حقيقية. عشان يبان لأي حد إنه مشروع حقيقي مش مجرد تيمبليت.
