### ISSUE TITLE
كيف أحصل على وظيفة في مجال الويب في حالة عدم اتمامي التعليم الجامعي؟

### ISSUE THREAD

**Issue by ahmedhosna95** [amrsekilly/AMA#6]
<div style="direction: rtl">
.

السلام عليكم يا باشمهندس عمرو .. اولا شكرًا كتير على مجهودات حضرتك والوقت اللي بتوفره لمساعدتنا
ثانيا عندي استفسار او سؤال مهم يخص وضعي في الوقت الحالي:
\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=
انا جونيور فرونت إند بتعلم بشكل ذاتي من اكثر من سنتين، عندي بورتفوليو وبكتب حاليا ال cv
وبملي بروفايل اللينكدان.. علشان أبدأ أقدم على وظائف بداية من أول اغسطس باذن الله
 لكني مش مكمل تعليمي الجامعي من 2013..
إزاي أوضح ده في السيفي بأفضل شكل بحيث الامور تيجي في صالحي في النهاية؟
.. وهل في نصايح معينة لوضعي ده تحسن فرصي في الحصول على وظيفة بمقابل جيد أو حتى القبول في أي وظيفة في الويب اقدر اصرف منها على نفسي وانا بتعلم؟.. 

تفاصيل اخرى:
\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=

- انا مستوايا كويس الحمدلله كبداية وبشهادة اكثر من حد شغال في المجال، وبحب المجال جدا من زمان جدا كهواية..
- مشاريعي كلها عملتها بغرض التدريب والممارسة ولسة ماشتغلتش بالفعل سواء شغل حر او مكتبي..
- حاليا بصقل مهاراتي في الفرونت إند من خلال تعلم مكتبة  
React.js و Next.js 
وناوي بعدهم أراجع التراك اللي ماشي عليه بغرض تحسين وجهتي.
- لغتي الانجليزية متوسطة، لكن بتمكن من التعلم من خلال الكتب الانجليزية وكورسات منصات التعليم الالكتروني وبتابع الاندستري على تويتر وبتفاعل أحيانا بدون مشكلة..
- آخر بروجت كامل اشتغلت عليه: https://ahmedhosna.netlify.app/portfolio/writescape-mern/

---
استفسار آخر بخصوص استكمال الدراسة
\=\=\=\=\=\=\=\=\=\=\=\=\=\=\=

 لو حابب اكمل دراسة 
CS
إيه أفضل الخيارات المتاحة ليا؟ تعليم مفتوح؟ ولا اسافر ولا تعليم عن بعد ولا اكمل دراسة ذاتية بشكل منهجي اكتر؟

وشكرًا مرة تانية ♥

</div>

**Comment by ahmedhosna95** [comment]
وعليكم السلام يا باشمهندس.. انا المفروض كنت دفعة 2013/2017.. تجارة عربي، ووقفت دراسة في الترم الاول من سنة اولى، الكلام ده في ديسمبر 2013/ يناير 2014.. 
لا معملتش وقف فيد.. كل اللي حصل إني سيبت ورقي على أمل اني هأجل سنة واحدة وابقى احل الموضوع كمان سنة، لكن من وقتها لغاية النهاردة ماكملتش دراسة خالص.. وماعييش ما يثبت اني كنت في الكلية وماعتقدش ان ورقي اللي هناك ممكن يفيدني في شيء.. كأني مادخلتهاش تمامًا..
وفي اللحظة دي انا عمري 25 سنة بالضبط

شخص في المجال نصحني وقالي ماتذكرش تعليمك في السي في او في اي مكان الا لو انطلب منك بشكل صريح تذكر موقفك من التعليم وتوضح السبب لو الانترفيوور سأل بعد ما أتخطى مرحلة قبول السيفي وتحديد انترفيو
لكني ببص لقدام، وببص لحلول فعلية علشان دنيتي في المستقبل تمشي بدون عرقلة لأني حابب ان الكارير بتاعي يكون في الويب
فأنا عاوز أعرف إيه أفضل شيء ممكن اعمله ويفيدني في حالتي دي في الوقت الحالي وفي المستقبل.. مع العلم اني عندي نية أكمل تعليم تخصص علوم كمبيوتر.. لكن ده هيحصل وانا بصرف على نفسي.. فالبتالي محتاج الشغل اللي يوفرلي ده ومن خلاله اقدر اكمل تعليم..
ماعنديش فكرة عن اذا كان الشغل الحر ممكن يساعدني ولا لا ولكن انا برضك في نفسك الوقت بدور على فرص عاجلة للالتحاق بأي وظيفة في المجال لأني عاطل لأكثر من 6 شهور ومحتاج دخل شهري ومحتاج اجدد الجهاز اللي بشتغل عليه علشان اقدر اكمل.. وفي نفس الوقت انا شايف ان مهاراتي تؤهلني اشتغل بعد ما شفت ناس كتير خريجة كليات وشغالة في شركات ومستواها يوازي مستوايا أو اقل..
فإيه اقتراحات حضرتك؟

آسف على الإطالة وشكرا لتجاوب حضرتك..

**Comment by amrsekilly** [comment]
أسف على التأخير. هو فعلا فالحالة ده متكتبش التعليم فالشهادة واتكلم عنه فالانترفيو لو سألوك.

بالنسبة للفريلانس فممكن يساعدك. وبالنسبة للشغل فشركات فمصر، معظم الشركات دلوقتي مش بتهتم بالشهادة لو معاك إللي يعوضها من الخبرة.

ربنا معاك وقولي لو احتاجت أي حاجة 🙏🏻

@ahmedhosna95

**Comment by ahmedhosna95** [comment]
متشكر أوي يا باشمهندس
هحتاج بس مساعدة حضرتك في مراجعة بروفايلي على لينكدان والريزوم بتاعتي في أي وقت حضرتك فاضي فيه.. وهكون شاكر جدًا ♥
https://www.linkedin.com/in/ahmedhosna95/
[ResumeAhmedNasr.pdf](https://github.com/amrsekilly/AMA/files/4971096/ResumeAhmedNasr.pdf)

**Comment by amrsekilly** [comment]
@ahmedhosna95 can I make a YouTube video about this?

**Comment by ahmedhosna95** [comment]
Sure, no problem.

**Comment by ahmedhosna95** [comment]
هستأذنك بس يا باشمهندس عمر لو ينفع تخفي الإشيو دي أو تحذفها، علشان ظاهرة في بروفايلي بس ومش لطيفة خالص :D
وشكرًا لحضرتك ♥
