### ISSUE TITLE
Eng/ Amr Sekilly

### ISSUE THREAD

**Issue by Muhamed-Mousa** [amrsekilly/AMA#7]
لو سمحت كنت عايز اسأل حضرتك علي شوية تفاصيل في اللغه اللي انا بتعلمها دلوقتي انا ذاكرت 
react
و معنديش خبره في ال
 html css js
 كافيه بس انا فاهمه اخدتهم 
basics
 و ذاكرة 
react redux 
ووقفت لحد هنا هل ممكن الاقي شغل بيها ولا اكمل لحد فين عشان ابتدي علي الاقل اشوف
 remote jop 
انا عايز استفيد من خبرة حضرتك ياباشمهندس

**Comment by amrsekilly** [comment]
@Muhamed-Mousa 

چافاسكريبت أهم حاجة المفروض تركز عليها. لازم تبقى قوي فيها قبل متتعلم أي frameworks 

وبالنسبة للشغل الريموت أنااتكلمت فالموضوع ده فآخر فيديو فاتفرج عليه وقولي لو فيه حاجة مش واضحة.
